language: node_js
node_js:
- "0.10"
 
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
 
before_script:
- npm install jpm -g
- cd ..
- url="http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-36.0a1.en-US.linux-x86_64.tar.bz2"
- wget -O firefox.tar.bz2 "$url"
- bzip2 -cd firefox.tar.bz2 | tar xvf -
- cd $TRAVIS_BUILD_DIR
 
script:
- export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
- jpm test -v

